import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :fileonchain, FileonchainWeb.Endpoint,
url: [host: System.get_env("PHX_HOST") || "localhost"],
  render_errors: [
    formats: [html: FileonchainWeb.ErrorHTML, json: FileonchainWeb.ErrorJSON],
    layout: false
  ],
  cache_static_manifest: "priv/static/cache_manifest.json",
  debug_errors: true

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Fileonchain.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Configure Swoosh for email sending
config :fileonchain, Fileonchain.Mailer,
  adapter: Swoosh.Adapters.SMTP,
  relay: System.get_env("SMTP_HOST") || "smtp",
  port: String.to_integer(System.get_env("SMTP_PORT") || "1025"),
  username: nil,
  password: nil,
  ssl: false,
  tls: :never,
  auth: :never,
  retries: 2,
  no_mx_lookups: false

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
