import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :fileonchain, FileonchainWeb.Endpoint,
url: [host: System.get_env("PHX_HOST") || "*.fileonchain.org", host: "*.fileonchain.org"],
  render_errors: [
    formats: [html: FileonchainWeb.ErrorHTML, json: FileonchainWeb.ErrorJSON],
    layout: false
  ],
  cache_static_manifest: "priv/static/cache_manifest.json",
  code_reloader: true,
  debug_errors: true,
  check_origin: [
    "https://fileonchain.org",
    "https://*.fileonchain.org",
    "https://seashell-app-v9acv.ondigitalocean.app"
  ]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Fileonchain.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Watch static and templates for browser reloading.
config :fileonchain, FileonchainWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/fileonchain_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
